structname: "Mock{{.InterfaceName}}"
filename: "{{.SrcPackageName}}_mock.gen.go"
dir: "{{.InterfaceDir}}"
pkgname: "{{.SrcPackageName}}"
inpackage: True
packages:
  jelly/pkg/store:
    interfaces:
      Storage:
